# Generated by Django 3.2.3 on 2021-05-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0002_auto_20210528_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='individuals',
            field=models.ManyToManyField(null=True, to='research_app.Individual'),
        ),
    ]
