# Generated by Django 3.2.3 on 2021-05-29 14:17

from django.db import migrations, models  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0003_alter_population_individuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='population',
            name='individuals',
            field=models.ManyToManyField(to='research_app.Individual'),
        ),
    ]
